version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_USERNAME: 'postgres'
      POSTGRES_DB: 'proposal'
    ports:
      - '5432:5432'
  # app:
  #   build: .
